# Generated by Django 5.1.5 on 2025-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_worldbankdata_delete_imfdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCommonsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WorldBankData",
        ),
    ]
